[package]
name = "identifiers"
version = "0.1.0"
authors = ["Paul Mucur <paul@altmetric.com>"]
description = "Library for handling and extracting scholarly identifiers from text."
readme = "README.md"
license = "MIT"

[dependencies]
lazy_static = "0.2.2"
regex = "0.2.1"
